language: python
python:
  - "3.6"            
dist: xenial
addons:
  chrome: stable
  
install:
  - wget -N http://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver⋮
  - pip install -r requirements.txt

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - pytest -s  
after_script:
  - ls *.zip
  - rm *.zip
