language: python
python:
  - "3.6"            
dist: xenial
addons:
  chrome: stable
  
before_install:
 - cd /home/travis/build/ucgmsim/
 - git clone https://github.com/ucgmsim/qcore.git

install:
  - wget -N http://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver⋮
  - pip install -r /home/travis/build/ucgmsim/seistech_psha_frontend/requirements.txt
  - pip install --no-deps ./qcore
  - export DEPLOY_NAME=`git rev-parse --abbrev-ref HEAD |awk -F'_' '{print $2}'`
  - echo $DEPLOY_NAME
  - export HOST_NAME=`hostname`

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - cd /home/travis/build/ucgmsim/seistech_psha_frontend
  - pytest -s  
after_script:
  - ls *.zip
  - rm *.zip
