language: python
python:
  - "3.6"            
dist: xenial
addons:
  chrome: stable
  
before_install:
  - echo `hostname`
  - export HOST_NAME=`hostname`
  - echo `pwd`
  - export BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH_NAME"
    #  - export DEPLOY_NAME=`python scripts/get_deploy_name.py $BRANCH_NAME`
  - export DEPLOY_NAME=psha-test
  - echo $DEPLOY_NAME
  - pip install pexpect
  - python scripts/ec2_send_cmd.py "$EC2USER" "$EC2PASSWD" "cd /home/ec2-user/seistech/docker/$BRANCH_NAME;../Dockerise.sh $BRANCH_NAME 5102 5002"
  - cd /home/travis/build/ucgmsim/
  - git clone https://github.com/ucgmsim/qcore.git

install:
  - wget -N http://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver⋮
  - pip install -r /home/travis/build/ucgmsim/seistech_psha_frontend/requirements.txt
  - pip install --no-deps ./qcore

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - cd /home/travis/build/ucgmsim/seistech_psha_frontend
  - sleep 5
  - echo "Testing $DEPLOY_NAME"
  - pytest -s  
after_script:
  - ls *.zip
  - rm *.zip
